# Generated by Django 4.2.9 on 2026-03-14 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "__first__"),
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcontract",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Contrato",
                "verbose_name_plural": "historical Contratos",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpayment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Pagamento",
                "verbose_name_plural": "historical Pagamentos",
            },
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="lead_id",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="reservation_id",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="unit_id",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="vendor_id",
        ),
        migrations.RemoveField(
            model_name="historicalpayment",
            name="contract_id",
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="crm.lead",
                verbose_name="Lead / Comprador",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="crm.unitreservation",
                verbose_name="Reserva de origem",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.unit",
                verbose_name="Unidade",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendedor responsável",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayment",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracts.contract",
                verbose_name="Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
