# Generated by Django 4.2.9 on 2026-03-14 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0002_alter_historicalcontract_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignatureRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expira a")),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Assinado a"
                    ),
                ),
                (
                    "signature_png_s3_key",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="S3 key da Assinatura"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "signed_by_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Assinado por (Nome)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("SIGNED", "Assinado"),
                            ("EXPIRED", "Expirado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_requests",
                        to="contracts.contract",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Assinatura",
                "verbose_name_plural": "Pedidos de Assinatura",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalSignatureRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Actualizado em"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expira a")),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Assinado a"
                    ),
                ),
                (
                    "signature_png_s3_key",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="S3 key da Assinatura"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "signed_by_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Assinado por (Nome)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("SIGNED", "Assinado"),
                            ("EXPIRED", "Expirado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contracts.contract",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pedido de Assinatura",
                "verbose_name_plural": "historical Pedidos de Assinatura",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="contract",
            name="signature_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signed_contract",
                to="contracts.signaturerequest",
                verbose_name="Pedido de Assinatura",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="signature_request",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracts.signaturerequest",
                verbose_name="Pedido de Assinatura",
            ),
        ),
    ]
