# Generated by Django 4.2.9 on 2026-04-20 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "contracts",
            "0004_alter_contract_created_at_alter_contract_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Template"),
                ),
                (
                    "html_content",
                    models.TextField(
                        help_text="Use {{ variable }} para placeholders",
                        verbose_name="Conteúdo HTML",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Template Padrão"),
                ),
            ],
            options={
                "verbose_name": "Template de Contrato",
                "verbose_name_plural": "Templates de Contrato",
            },
        ),
        migrations.CreateModel(
            name="PaymentPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Padrão"),
                ),
                (
                    "deposit_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Sinal (%)",
                    ),
                ),
                (
                    "final_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Pagamento Final (%)",
                    ),
                ),
                (
                    "installments_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Prestações"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Padrão Padrão"),
                ),
            ],
            options={
                "verbose_name": "Padrão de Pagamento",
                "verbose_name_plural": "Padrões de Pagamento",
            },
        ),
        migrations.CreateModel(
            name="HistoricalPaymentPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Padrão"),
                ),
                (
                    "deposit_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Sinal (%)",
                    ),
                ),
                (
                    "final_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Pagamento Final (%)",
                    ),
                ),
                (
                    "installments_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Prestações"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Padrão Padrão"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Padrão de Pagamento",
                "verbose_name_plural": "historical Padrões de Pagamento",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContractTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Template"),
                ),
                (
                    "html_content",
                    models.TextField(
                        help_text="Use {{ variable }} para placeholders",
                        verbose_name="Conteúdo HTML",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Template Padrão"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Template de Contrato",
                "verbose_name_plural": "historical Templates de Contrato",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="contract",
            name="payment_pattern",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="contracts.paymentpattern",
                verbose_name="Padrão de pagamento",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="contracts.contracttemplate",
                verbose_name="Template utilizado",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="payment_pattern",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracts.paymentpattern",
                verbose_name="Padrão de pagamento",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracts.contracttemplate",
                verbose_name="Template utilizado",
            ),
        ),
    ]
