# Generated by Django 4.2.9 on 2026-03-14 06:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("floors_count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Edifício",
                "verbose_name_plural": "Edifícios",
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                ("number", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Piso",
                "verbose_name_plural": "Pisos",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBuilding",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Actualizado em"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("floors_count", models.PositiveIntegerField(default=1)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Edifício",
                "verbose_name_plural": "historical Edifícios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFloor",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Actualizado em"
                    ),
                ),
                ("number", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Piso",
                "verbose_name_plural": "historical Pisos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProject",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Actualizado em"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome do Projecto"),
                ),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Em Planeamento"),
                            ("LICENSING", "Em Licenciamento"),
                            ("CONSTRUCTION", "Em Construção"),
                            ("COMPLETED", "Concluído"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Coordenadas GPS do projecto",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "land_parcel",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Polígono do terreno",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(default="Praia", max_length=100)),
                ("island", models.CharField(default="Santiago", max_length=50)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("expected_completion", models.DateField(blank=True, null=True)),
                ("actual_completion", models.DateField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Projecto",
                "verbose_name_plural": "historical Projectos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome do Projecto"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Em Planeamento"),
                            ("LICENSING", "Em Licenciamento"),
                            ("CONSTRUCTION", "Em Construção"),
                            ("COMPLETED", "Concluído"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Coordenadas GPS do projecto",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "land_parcel",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Polígono do terreno",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(default="Praia", max_length=100)),
                ("island", models.CharField(default="Santiago", max_length=50)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("expected_completion", models.DateField(blank=True, null=True)),
                ("actual_completion", models.DateField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Projecto",
                "verbose_name_plural": "Projectos",
                "ordering": ["-created_at"],
            },
        ),
    ]
