# Generated by Django 4.2.9 on 2026-04-20 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "projects",
            "0003_alter_building_created_at_alter_building_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Ficheiro técnico",
                        upload_to="projects/documents/%Y/%m/",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PLAN", "Planta Arquitetónica"),
                            ("LICENSE", "Licença"),
                            ("CONTRACT", "Caderno de Encargos / Contrato"),
                            ("OTHER", "Outro"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_project_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Projecto",
                "verbose_name_plural": "Documentos de Projecto",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProjectDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "file",
                    models.TextField(help_text="Ficheiro técnico", max_length=100),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PLAN", "Planta Arquitetónica"),
                            ("LICENSE", "Licença"),
                            ("CONTRACT", "Caderno de Encargos / Contrato"),
                            ("OTHER", "Outro"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Documento de Projecto",
                "verbose_name_plural": "historical Documentos de Projecto",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
