# Generated by Django 4.2.9 on 2026-03-14 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImoCvWebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("lead_captured", "Lead Capturado"),
                            ("unit_viewed", "Unidade Visualizada"),
                            ("listing_updated", "Listing Actualizado"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "imocv_listing_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID imo.cv"
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Payload")),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processado em"
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, verbose_name="Erro de processamento"),
                ),
            ],
            options={
                "verbose_name": "Webhook Log imo.cv",
                "verbose_name_plural": "Webhook Logs imo.cv",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="marketplace_event_t_0230f3_idx",
                    ),
                    models.Index(
                        fields=["processed_at"], name="marketplace_process_89dc78_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalMarketplaceListing",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Actualizado em"
                    ),
                ),
                (
                    "imocv_listing_id",
                    models.CharField(
                        blank=True,
                        help_text="ID do anúncio no imo.cv",
                        max_length=100,
                        verbose_name="ID imo.cv",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_SYNC", "Pendente Sync"),
                            ("PUBLISHED", "Publicado"),
                            ("PAUSED", "Pausado"),
                            ("REMOVED", "Removido"),
                        ],
                        default="PENDING_SYNC",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última sincronização"
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Último erro de sincronização",
                        verbose_name="Erro de sincronização",
                    ),
                ),
                (
                    "price_override_cve",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço publicado no imo.cv. Se None, usa Unit.pricing.final_price_cve",
                        max_digits=14,
                        null=True,
                        verbose_name="Preço publicado (CVE)",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publicado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.unit",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Listing Marketplace",
                "verbose_name_plural": "historical Listings Marketplace",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MarketplaceListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                (
                    "imocv_listing_id",
                    models.CharField(
                        blank=True,
                        help_text="ID do anúncio no imo.cv",
                        max_length=100,
                        verbose_name="ID imo.cv",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_SYNC", "Pendente Sync"),
                            ("PUBLISHED", "Publicado"),
                            ("PAUSED", "Pausado"),
                            ("REMOVED", "Removido"),
                        ],
                        default="PENDING_SYNC",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última sincronização"
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Último erro de sincronização",
                        verbose_name="Erro de sincronização",
                    ),
                ),
                (
                    "price_override_cve",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço publicado no imo.cv. Se None, usa Unit.pricing.final_price_cve",
                        max_digits=14,
                        null=True,
                        verbose_name="Preço publicado (CVE)",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publicado em"
                    ),
                ),
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing",
                        to="inventory.unit",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Marketplace",
                "verbose_name_plural": "Listings Marketplace",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="marketplace_status_91fad9_idx"
                    ),
                    models.Index(
                        fields=["imocv_listing_id"],
                        name="marketplace_imocv_l_81b21e_idx",
                    ),
                ],
            },
        ),
    ]
