# Generated by Django 4.2.9 on 2026-03-14 06:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDailyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Actualizado em"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Data")),
                (
                    "summary",
                    models.TextField(
                        help_text="Descrição das actividades realizadas no dia.",
                        verbose_name="Resumo",
                    ),
                ),
                (
                    "progress_pct",
                    models.PositiveSmallIntegerField(
                        help_text="Percentagem de conclusão estimada no momento do relatório.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Avanço (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("SUBMITTED", "Submetido"),
                            ("APPROVED", "Aprovado"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: Ensolarado, Chuva fraca, Vento forte.",
                        max_length=50,
                        verbose_name="Condições meteorológicas",
                    ),
                ),
                (
                    "workers_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Total de trabalhadores presentes no local no dia.",
                        verbose_name="Número de trabalhadores",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Engenheiro ou técnico responsável pelo relatório.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Opcional — relatório pode ser ao nível do projecto inteiro.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.building",
                        verbose_name="Edifício",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                        verbose_name="Projecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Diário de Obra",
                "verbose_name_plural": "historical Diários de Obra",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Data")),
                (
                    "summary",
                    models.TextField(
                        help_text="Descrição das actividades realizadas no dia.",
                        verbose_name="Resumo",
                    ),
                ),
                (
                    "progress_pct",
                    models.PositiveSmallIntegerField(
                        help_text="Percentagem de conclusão estimada no momento do relatório.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Avanço (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("SUBMITTED", "Submetido"),
                            ("APPROVED", "Aprovado"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: Ensolarado, Chuva fraca, Vento forte.",
                        max_length=50,
                        verbose_name="Condições meteorológicas",
                    ),
                ),
                (
                    "workers_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Total de trabalhadores presentes no local no dia.",
                        verbose_name="Número de trabalhadores",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Engenheiro ou técnico responsável pelo relatório.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional — relatório pode ser ao nível do projecto inteiro.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_reports",
                        to="projects.building",
                        verbose_name="Edifício",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_reports",
                        to="projects.project",
                        verbose_name="Projecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diário de Obra",
                "verbose_name_plural": "Diários de Obra",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ConstructionProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                (
                    "progress_pct",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Overall completion % derived from approved daily reports.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Avanço geral (%)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualização"
                    ),
                ),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="projects.building",
                        verbose_name="Edifício",
                    ),
                ),
                (
                    "last_report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Most recent approved DailyReport that updated this snapshot.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="construction.dailyreport",
                        verbose_name="Último relatório aprovado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Construção",
                "verbose_name_plural": "Progressos de Construção",
            },
        ),
        migrations.CreateModel(
            name="ConstructionPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                (
                    "s3_key",
                    models.CharField(
                        help_text="S3 object key: tenants/{slug}/construction/...",
                        max_length=500,
                        verbose_name="Chave S3",
                    ),
                ),
                (
                    "thumbnail_s3_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 object key for the auto-generated thumbnail.",
                        max_length=500,
                        verbose_name="Chave S3 (miniatura)",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Legenda"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Carregado por",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="construction.dailyreport",
                        verbose_name="Relatório",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotografia de Obra",
                "verbose_name_plural": "Fotografias de Obra",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dailyreport",
            index=models.Index(
                fields=["project", "-date"], name="constr_rpt_proj_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyreport",
            index=models.Index(
                fields=["status", "-date"], name="constr_rpt_status_date_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyreport",
            unique_together={("project", "building", "date")},
        ),
        migrations.AddIndex(
            model_name="constructionphoto",
            index=models.Index(
                fields=["report", "-created_at"], name="construction_photo_report_idx"
            ),
        ),
    ]
