# Generated by Django 4.2.9 on 2026-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionphoto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="constructionphoto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="constructionprogress",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="constructionprogress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="created_at",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="updated_at",
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
