# Generated by Django 4.2.9 on 2026-04-20 16:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("construction", "0003_constructiontask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="constructionphoto",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="constructionphoto",
            name="report",
        ),
        migrations.RemoveField(
            model_name="constructionprogress",
            name="building",
        ),
        migrations.RemoveField(
            model_name="constructionprogress",
            name="last_report",
        ),
        migrations.RemoveField(
            model_name="constructionproject",
            name="building",
        ),
        migrations.RemoveField(
            model_name="constructionproject",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="constructionproject",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="constructionproject",
            name="project",
        ),
        migrations.RemoveField(
            model_name="constructionproject",
            name="unit",
        ),
        migrations.AlterUniqueTogether(
            name="dailyreport",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dailyreport",
            name="author",
        ),
        migrations.RemoveField(
            model_name="dailyreport",
            name="building",
        ),
        migrations.RemoveField(
            model_name="dailyreport",
            name="project",
        ),
        migrations.RemoveField(
            model_name="historicalconstructionproject",
            name="building",
        ),
        migrations.RemoveField(
            model_name="historicalconstructionproject",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="historicalconstructionproject",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalconstructionproject",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalconstructionproject",
            name="project",
        ),
        migrations.RemoveField(
            model_name="historicalconstructionproject",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="historicaldailyreport",
            name="author",
        ),
        migrations.RemoveField(
            model_name="historicaldailyreport",
            name="building",
        ),
        migrations.RemoveField(
            model_name="historicaldailyreport",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaldailyreport",
            name="project",
        ),
        migrations.RenameIndex(
            model_name="constructionphase",
            new_name="constructio_project_621b0a_idx",
            old_name="constr_phase_project_status_idx",
        ),
        migrations.RenameIndex(
            model_name="constructionphase",
            new_name="constructio_project_4efe34_idx",
            old_name="constr_phase_project_order_idx",
        ),
        migrations.RenameIndex(
            model_name="constructiontask",
            new_name="constructio_project_efa907_idx",
            old_name="constr_task_project_status_idx",
        ),
        migrations.RenameIndex(
            model_name="constructiontask",
            new_name="constructio_assigne_88f3cd_idx",
            old_name="constr_task_assignee_status_idx",
        ),
        migrations.RenameIndex(
            model_name="constructiontask",
            new_name="constructio_due_dat_fc34eb_idx",
            old_name="constr_task_due_date_idx",
        ),
        migrations.RenameIndex(
            model_name="constructiontask",
            new_name="constructio_phase_i_c0b528_idx",
            old_name="constr_task_phase_wbs_idx",
        ),
        migrations.RenameIndex(
            model_name="constructiontask",
            new_name="constructio_advance_fa7a39_idx",
            old_name="constr_task_adv_mode_idx",
        ),
        migrations.RenameIndex(
            model_name="cpmsnapshot",
            new_name="constructio_task_id_2a4857_idx",
            old_name="constr_cpm_task_critical_idx",
        ),
        migrations.RenameIndex(
            model_name="cpmsnapshot",
            new_name="constructio_calcula_8d8530_idx",
            old_name="constr_cpm_calculated_idx",
        ),
        migrations.RenameIndex(
            model_name="evmsnapshot",
            new_name="constructio_project_2a2736_idx",
            old_name="constr_evm_project_date_idx",
        ),
        migrations.RenameIndex(
            model_name="evmsnapshot",
            new_name="constructio_date_d6757d_idx",
            old_name="constr_evm_date_idx",
        ),
        migrations.RenameIndex(
            model_name="taskdependency",
            new_name="constructio_from_ta_44d833_idx",
            old_name="constr_dep_from_task_idx",
        ),
        migrations.RenameIndex(
            model_name="taskdependency",
            new_name="constructio_to_task_43aaee_idx",
            old_name="constr_dep_to_task_idx",
        ),
        migrations.RenameIndex(
            model_name="taskphoto",
            new_name="constructio_task_id_60cde2_idx",
            old_name="constr_photo_task_idx",
        ),
        migrations.RenameIndex(
            model_name="taskphoto",
            new_name="constructio_uploade_fd0039_idx",
            old_name="constr_photo_uploader_idx",
        ),
        migrations.RenameIndex(
            model_name="taskprogresslog",
            new_name="constructio_task_id_a085cd_idx",
            old_name="constr_proglog_task_idx",
        ),
        migrations.AlterField(
            model_name="constructionphase",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_phases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="constructiontask",
            name="bim_element_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de GUIDs IFC",
                verbose_name="IDs BIM (IFC)",
            ),
        ),
        migrations.AlterField(
            model_name="constructiontask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="constructiontask",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Duração planeada para CPM",
                verbose_name="Duração (dias)",
            ),
        ),
        migrations.AlterField(
            model_name="constructiontask",
            name="progress_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="0-100%",
                max_digits=5,
                verbose_name="Progresso (%)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="ac",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Custo real incorrido",
                max_digits=14,
                verbose_name="AC (Actual Cost)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="bac",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Orçamento total do projeto",
                max_digits=14,
                verbose_name="BAC (Budget at Completion)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="cpi",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text=">1 = abaixo orçamento, <1 = acima orçamento",
                max_digits=5,
                verbose_name="CPI (Cost Performance Index)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="cv",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="EV - AC",
                max_digits=14,
                verbose_name="CV (Cost Variance)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="eac",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Previsão de custo final",
                max_digits=14,
                verbose_name="EAC (Estimate at Completion)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="etc",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Estimativa para terminar",
                max_digits=14,
                verbose_name="ETC (Estimate to Complete)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="ev",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor ganho (trabalho realizado)",
                max_digits=14,
                verbose_name="EV (Earned Value)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="pv",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor planejado até a data",
                max_digits=14,
                verbose_name="PV (Planned Value)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="spi",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text=">1 = adiantado, <1 = atrasado",
                max_digits=5,
                verbose_name="SPI (Schedule Performance Index)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="sv",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="EV - PV",
                max_digits=14,
                verbose_name="SV (Schedule Variance)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="tcpi",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Índice necessário para cumprir orçamento",
                max_digits=5,
                null=True,
                verbose_name="TCPI (To-Complete Performance Index)",
            ),
        ),
        migrations.AlterField(
            model_name="evmsnapshot",
            name="vac",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="BAC - EAC",
                max_digits=14,
                verbose_name="VAC (Variance at Completion)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstructionphase",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Não Iniciado"),
                    ("IN_PROGRESS", "Em Execução"),
                    ("COMPLETED", "Concluído"),
                    ("BLOCKED", "Bloqueado"),
                ],
                db_index=True,
                default="NOT_STARTED",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstructiontask",
            name="bim_element_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de GUIDs IFC",
                verbose_name="IDs BIM (IFC)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstructiontask",
            name="due_date",
            field=models.DateField(db_index=True, verbose_name="Data Limite"),
        ),
        migrations.AlterField(
            model_name="historicalconstructiontask",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Duração planeada para CPM",
                verbose_name="Duração (dias)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstructiontask",
            name="overdue_notified",
            field=models.BooleanField(
                default=False, help_text="Notificação de atraso enviada"
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstructiontask",
            name="progress_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="0-100%",
                max_digits=5,
                verbose_name="Progresso (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstructiontask",
            name="reminder_sent",
            field=models.BooleanField(default=False, help_text="Lembrete enviado"),
        ),
        migrations.AlterField(
            model_name="historicalconstructiontask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("IN_PROGRESS", "Em Andamento"),
                    ("COMPLETED", "Concluído"),
                    ("BLOCKED", "Bloqueada"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstructiontask",
            name="wbs_code",
            field=models.CharField(
                help_text="Ex: 1.1, 1.2, 2.1...",
                max_length=20,
                verbose_name="Código WBS",
            ),
        ),
        migrations.AlterField(
            model_name="taskdependency",
            name="lag_days",
            field=models.IntegerField(
                default=0,
                help_text="Atraso entre tasks (positivo) ou overlap (negativo)",
                verbose_name="Lag (dias)",
            ),
        ),
        migrations.AlterField(
            model_name="taskprogresslog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data"),
        ),
        migrations.DeleteModel(
            name="ConstructionPhoto",
        ),
        migrations.DeleteModel(
            name="ConstructionProgress",
        ),
        migrations.DeleteModel(
            name="ConstructionProject",
        ),
        migrations.DeleteModel(
            name="DailyReport",
        ),
        migrations.DeleteModel(
            name="HistoricalConstructionProject",
        ),
        migrations.DeleteModel(
            name="HistoricalDailyReport",
        ),
    ]
