# Generated by Django 4.2.9 on 2026-04-21 10:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0004_projectdocument_historicalprojectdocument"),
        ("construction", "0005_recreate_dailyreport_constructionproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionphoto",
            name="s3_key",
            field=models.CharField(
                help_text="S3 object key: tenants/{slug}/construction/...",
                max_length=500,
                verbose_name="Chave S3",
            ),
        ),
        migrations.AlterField(
            model_name="constructionphoto",
            name="thumbnail_s3_key",
            field=models.CharField(
                blank=True,
                help_text="S3 object key for the auto-generated thumbnail.",
                max_length=500,
                verbose_name="Chave S3 (miniatura)",
            ),
        ),
        migrations.AlterField(
            model_name="constructionprogress",
            name="last_report",
            field=models.ForeignKey(
                blank=True,
                help_text="Most recent approved DailyReport that updated this snapshot.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="construction.dailyreport",
                verbose_name="Último relatório aprovado",
            ),
        ),
        migrations.AlterField(
            model_name="constructionprogress",
            name="progress_pct",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Overall completion % derived from approved daily reports.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Avanço geral (%)",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="author",
            field=models.ForeignKey(
                help_text="Engenheiro ou técnico responsável pelo relatório.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="building",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional — relatório pode ser ao nível do projecto inteiro.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_reports",
                to="projects.building",
                verbose_name="Edifício",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="progress_pct",
            field=models.PositiveSmallIntegerField(
                help_text="Percentagem de conclusão estimada no momento do relatório.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Avanço (%)",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weather",
            field=models.CharField(
                blank=True,
                help_text="Ex.: Ensolarado, Chuva fraca, Vento forte.",
                max_length=50,
                verbose_name="Condições meteorológicas",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="workers_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Total de trabalhadores presentes no local no dia.",
                verbose_name="Número de trabalhadores",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstructionproject",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Engenheiro ou técnico responsável pelo relatório.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="building",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Opcional — relatório pode ser ao nível do projecto inteiro.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.building",
                verbose_name="Edifício",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="progress_pct",
            field=models.PositiveSmallIntegerField(
                help_text="Percentagem de conclusão estimada no momento do relatório.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Avanço (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="summary",
            field=models.TextField(
                help_text="Descrição das actividades realizadas no dia.",
                verbose_name="Resumo",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="weather",
            field=models.CharField(
                blank=True,
                help_text="Ex.: Ensolarado, Chuva fraca, Vento forte.",
                max_length=50,
                verbose_name="Condições meteorológicas",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="workers_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Total de trabalhadores presentes no local no dia.",
                verbose_name="Número de trabalhadores",
            ),
        ),
    ]
