# Generated by Django 4.2.9 on 2026-03-19 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_tenantregistration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales_by_project", "Vendas por Projecto"),
                            ("crm_pipeline", "Pipeline CRM"),
                            ("payment_extract", "Extracto de Pagamentos"),
                            ("construction_report", "Relatório de Obra"),
                            ("unit_listing", "Listagem de Unidades"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel (.xlsx)"),
                            ("csv", "CSV"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, help_text="Filters applied to report"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "A processar"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, help_text="S3 presigned download URL"),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Download URL expires at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.client"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-created_at"],
                        name="core_report_tenant__7e39a0_idx",
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="core_report_created_fee209_idx",
                    ),
                ],
            },
        ),
    ]
