# Generated by Django 4.2.9 on 2026-03-14 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome da Empresa"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used for S3 prefix and subdomain", unique=True
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.CharField(
                        default="CV", help_text="ISO 3166-1 alpha-2", max_length=2
                    ),
                ),
                ("currency", models.CharField(default="CVE", max_length=3)),
                (
                    "timezone",
                    models.CharField(default="Atlantic/Cape_Verde", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente (Tenant)",
                "verbose_name_plural": "Clientes (Tenants)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#1E40AF", max_length=7)),
                ("max_projects", models.PositiveIntegerField(default=5)),
                ("max_units", models.PositiveIntegerField(default=500)),
                ("max_users", models.PositiveIntegerField(default=20)),
                ("imo_cv_api_key", models.CharField(blank=True, max_length=200)),
                (
                    "imocv_enabled",
                    models.BooleanField(
                        default=False, help_text="Activar integração com imo.cv"
                    ),
                ),
                (
                    "imocv_auto_publish",
                    models.BooleanField(
                        default=False,
                        help_text="Publicar automaticamente unidades AVAILABLE no imo.cv",
                    ),
                ),
                ("whatsapp_phone_id", models.CharField(blank=True, max_length=50)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurações do Tenant",
                "verbose_name_plural": "Configurações dos Tenants",
            },
        ),
        migrations.CreateModel(
            name="HistoricalTenantSettings",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#1E40AF", max_length=7)),
                ("max_projects", models.PositiveIntegerField(default=5)),
                ("max_units", models.PositiveIntegerField(default=500)),
                ("max_users", models.PositiveIntegerField(default=20)),
                ("imo_cv_api_key", models.CharField(blank=True, max_length=200)),
                (
                    "imocv_enabled",
                    models.BooleanField(
                        default=False, help_text="Activar integração com imo.cv"
                    ),
                ),
                (
                    "imocv_auto_publish",
                    models.BooleanField(
                        default=False,
                        help_text="Publicar automaticamente unidades AVAILABLE no imo.cv",
                    ),
                ),
                ("whatsapp_phone_id", models.CharField(blank=True, max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Configurações do Tenant",
                "verbose_name_plural": "historical Configurações dos Tenants",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDomain",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=253)),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Domínio",
                "verbose_name_plural": "historical Domínios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalClient",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome da Empresa"),
                ),
                (
                    "slug",
                    models.SlugField(help_text="Used for S3 prefix and subdomain"),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.CharField(
                        default="CV", help_text="ISO 3166-1 alpha-2", max_length=2
                    ),
                ),
                ("currency", models.CharField(default="CVE", max_length=3)),
                (
                    "timezone",
                    models.CharField(default="Atlantic/Cape_Verde", max_length=50),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Cliente (Tenant)",
                "verbose_name_plural": "historical Clientes (Tenants)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domínio",
                "verbose_name_plural": "Domínios",
                "ordering": ["domain"],
            },
        ),
    ]
