# Generated by Django 4.2.9 on 2026-03-14 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PLAN_UPGRADED", "Plano Actualizado"),
                            ("PLAN_DOWNGRADED", "Plano Rebaixado"),
                            ("LIMIT_HIT", "Limite Atingido"),
                            ("TRIAL_STARTED", "Trial Iniciado"),
                            ("TRIAL_ENDED", "Trial Terminado"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                ("from_plan", models.CharField(blank=True, max_length=20)),
                ("to_plan", models.CharField(blank=True, max_length=20)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_events",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Plano",
                "verbose_name_plural": "Eventos de Plano",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="plan_event_tenant_date_idx",
                    )
                ],
            },
        ),
    ]
