# Generated by Django 4.2.9 on 2026-03-16 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_add_plan_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Nome da Empresa"),
                ),
                (
                    "subdomain",
                    models.CharField(
                        help_text="Será usado como schema_name e subdomínio (ex: subdomain.imos.cv)",
                        max_length=63,
                        unique=True,
                        verbose_name="Subdomínio",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("starter", "Starter (Gratuito)"),
                            ("pro", "Pro (€49/mês)"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="starter",
                        max_length=20,
                        verbose_name="Plano",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email de Contacto"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Telefone / WhatsApp"),
                ),
                (
                    "country",
                    models.CharField(
                        default="CV",
                        help_text="ISO 3166-1 alpha-2 (CV, AO, SN)",
                        max_length=2,
                        verbose_name="País",
                    ),
                ),
                (
                    "verification_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token de Verificação",
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(verbose_name="Token Expira Em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_VERIFICATION", "Pendente de Verificação"),
                            ("VERIFIED", "Verificado"),
                            ("PROVISIONING", "A Provisionar"),
                            ("ACTIVE", "Activo"),
                            ("REJECTED", "Rejeitado"),
                        ],
                        db_index=True,
                        default="PENDING_VERIFICATION",
                        max_length=25,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado Em"),
                ),
                (
                    "provisioned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Provisionado Em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Registo de Tenant",
                "verbose_name_plural": "Registos de Tenants",
                "ordering": ["-created_at"],
            },
        ),
    ]
