# Generated by Django 4.2.9 on 2026-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenantregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltenantsettings",
            name="imo_cv_api_key",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="imo_cv_api_key",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
