# Generated by Django 4.2.9 on 2026-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_alter_historicaltenantsettings_imo_cv_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltenantsettings",
            name="whatsapp_access_token",
            field=models.CharField(
                blank=True, help_text="Token permanente do Meta App", max_length=512
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="whatsapp_access_token",
            field=models.CharField(
                blank=True, help_text="Token permanente do Meta App", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="planevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PLAN_UPGRADED", "Plano Actualizado"),
                    ("PLAN_DOWNGRADED", "Plano Rebaixado"),
                    ("LIMIT_HIT", "Limite Atingido"),
                    ("TRIAL_STARTED", "Trial Iniciado"),
                    ("TRIAL_ENDED", "Trial Terminado"),
                    ("IMPERSONATED", "Impersonation"),
                ],
                db_index=True,
                max_length=25,
            ),
        ),
    ]
