# Generated by Django 4.2.9 on 2026-03-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_alter_historicalcontract_options_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalpaymentplan",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Plano de Pagamento",
                "verbose_name_plural": "historical Planos de Pagamento",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpaymentplanitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Item do Plano de Pagamento",
                "verbose_name_plural": "historical Itens do Plano de Pagamento",
            },
        ),
        migrations.RemoveField(
            model_name="historicalpaymentplan",
            name="contract_id",
        ),
        migrations.RemoveField(
            model_name="historicalpaymentplanitem",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="historicalpaymentplanitem",
            name="plan_id",
        ),
        migrations.AddField(
            model_name="historicalpaymentplan",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracts.contract",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="historicalpaymentplanitem",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracts.payment",
                verbose_name="Pagamento liquidado",
            ),
        ),
        migrations.AddField(
            model_name="historicalpaymentplanitem",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="payments.paymentplan",
                verbose_name="Plano",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpaymentplan",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalpaymentplanitem",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
