# Generated by Django 4.2.9 on 2026-03-14 06:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("code", models.CharField(help_text="Ex: BLK-A-P3-DT2", max_length=30)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponível"),
                            ("RESERVED", "Reservado"),
                            ("CONTRACT", "Contrato Assinado"),
                            ("SOLD", "Vendido"),
                            ("MAINTENANCE", "Manutenção"),
                        ],
                        default="AVAILABLE",
                        max_length=15,
                    ),
                ),
                (
                    "area_bruta",
                    models.DecimalField(
                        decimal_places=2, help_text="m² brutos", max_digits=8
                    ),
                ),
                (
                    "area_util",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="m² úteis",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        blank=True, help_text="Norte, Sul, Mar, etc.", max_length=20
                    ),
                ),
                ("floor_number", models.IntegerField(default=0)),
                (
                    "bim_guid",
                    models.CharField(
                        blank=True, help_text="IFC element GUID", max_length=100
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Unidade",
                "verbose_name_plural": "historical Unidades",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUnitPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "price_cve",
                    models.DecimalField(
                        decimal_places=2, help_text="Preço em CVE", max_digits=12
                    ),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço em EUR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Sem Desconto"),
                            ("PERCENT", "Percentagem"),
                            ("FIXED", "Valor Fixo"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical unit pricing",
                "verbose_name_plural": "historical unit pricings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="Ex: BLK-A-P3-DT2", max_length=30)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponível"),
                            ("RESERVED", "Reservado"),
                            ("CONTRACT", "Contrato Assinado"),
                            ("SOLD", "Vendido"),
                            ("MAINTENANCE", "Manutenção"),
                        ],
                        default="AVAILABLE",
                        max_length=15,
                    ),
                ),
                (
                    "area_bruta",
                    models.DecimalField(
                        decimal_places=2, help_text="m² brutos", max_digits=8
                    ),
                ),
                (
                    "area_util",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="m² úteis",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        blank=True, help_text="Norte, Sul, Mar, etc.", max_length=20
                    ),
                ),
                ("floor_number", models.IntegerField(default=0)),
                (
                    "bim_guid",
                    models.CharField(
                        blank=True, help_text="IFC element GUID", max_length=100
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10)),
                ("bedrooms", models.PositiveSmallIntegerField(default=0)),
                ("bathrooms", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UnitPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price_cve",
                    models.DecimalField(
                        decimal_places=2, help_text="Preço em CVE", max_digits=12
                    ),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço em EUR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Sem Desconto"),
                            ("PERCENT", "Percentagem"),
                            ("FIXED", "Valor Fixo"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="inventory.unit",
                    ),
                ),
            ],
        ),
    ]
