# Generated by Django 4.2.9 on 2026-03-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["status"], name="inventory_unit_status_idx"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["status", "is_deleted"], name="inventory_unit_status_del_idx"
            ),
        ),
    ]
