# Generated by Django 4.2.9 on 2026-04-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_unitoccurrence"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="unitoccurrence",
            new_name="inventory_u_status_2eeb3e_idx",
            old_name="inventory_occ_status_priority_idx",
        ),
        migrations.RenameIndex(
            model_name="unitoccurrence",
            new_name="inventory_u_unit_id_e62425_idx",
            old_name="inventory_occ_unit_status_idx",
        ),
        migrations.AlterField(
            model_name="historicalunitoccurrence",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
