# Generated by Django 4.2.9 on 2026-03-14 06:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Novo"),
                            ("CONTACTED", "Contactado"),
                            ("QUALIFIED", "Qualificado"),
                            ("LOST", "Perdido"),
                            ("CONVERTED", "Convertido (Venda)"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEB", "Website"),
                            ("INSTAGRAM", "Instagram"),
                            ("FACEBOOK", "Facebook"),
                            ("REFERRAL", "Referência"),
                            ("IMOCV", "imo.cv"),
                            ("OTHER", "Outro"),
                        ],
                        default="WEB",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "Novo"),
                            ("contacted", "Contactado"),
                            ("visit_scheduled", "Visita Agendada"),
                            ("proposal_sent", "Proposta Enviada"),
                            ("negotiation", "Negociação"),
                            ("won", "Ganho"),
                            ("lost", "Perdido"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("lost_reason", models.TextField(blank=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("preferred_typology", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("visit_date", models.DateTimeField(blank=True, null=True)),
                ("proposal_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="% comissão do vendedor",
                        max_digits=5,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interested_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="inventory.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnitReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activa"),
                            ("EXPIRED", "Expirada"),
                            ("CONVERTED", "Convertida em Contrato"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Reserva expira automaticamente (default +48h)"
                    ),
                ),
                (
                    "deposit_amount_cve",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="crm.lead",
                    ),
                ),
                (
                    "reserved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventory.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("CALL", "Chamada"),
                            ("MEETING", "Reunião"),
                            ("EMAIL", "E-mail"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("summary", models.TextField()),
                ("is_completed", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interação",
                "verbose_name_plural": "Interações",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalUnitReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Actualizado em"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activa"),
                            ("EXPIRED", "Expirada"),
                            ("CONVERTED", "Convertida em Contrato"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Reserva expira automaticamente (default +48h)"
                    ),
                ),
                (
                    "deposit_amount_cve",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.lead",
                    ),
                ),
                (
                    "reserved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Reserva",
                "verbose_name_plural": "historical Reservas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLead",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Actualizado em"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Novo"),
                            ("CONTACTED", "Contactado"),
                            ("QUALIFIED", "Qualificado"),
                            ("LOST", "Perdido"),
                            ("CONVERTED", "Convertido (Venda)"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEB", "Website"),
                            ("INSTAGRAM", "Instagram"),
                            ("FACEBOOK", "Facebook"),
                            ("REFERRAL", "Referência"),
                            ("IMOCV", "imo.cv"),
                            ("OTHER", "Outro"),
                        ],
                        default="WEB",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "Novo"),
                            ("contacted", "Contactado"),
                            ("visit_scheduled", "Visita Agendada"),
                            ("proposal_sent", "Proposta Enviada"),
                            ("negotiation", "Negociação"),
                            ("won", "Ganho"),
                            ("lost", "Perdido"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("lost_reason", models.TextField(blank=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("preferred_typology", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("visit_date", models.DateTimeField(blank=True, null=True)),
                ("proposal_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="% comissão do vendedor",
                        max_digits=5,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interested_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Lead",
                "verbose_name_plural": "historical Leads",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Actualizado em"
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("CALL", "Chamada"),
                            ("MEETING", "Reunião"),
                            ("EMAIL", "E-mail"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("summary", models.TextField()),
                ("is_completed", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Interação",
                "verbose_name_plural": "historical Interações",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="unitreservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("unit",),
                name="unique_active_reservation_per_unit",
            ),
        ),
    ]
