# Generated by Django 4.2.9 on 2026-03-14 13:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallead",
            name="whatsapp_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="Lead pediu para não receber mensagens WhatsApp (LGPD/Lei 133/V/2019)",
            ),
        ),
        migrations.AddField(
            model_name="historicallead",
            name="whatsapp_opt_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="whatsapp_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="Lead pediu para não receber mensagens WhatsApp (LGPD/Lei 133/V/2019)",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="whatsapp_opt_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                ("name", models.CharField(max_length=100)),
                ("template_id_meta", models.CharField(max_length=100)),
                ("language", models.CharField(default="pt_PT", max_length=10)),
                ("variables", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Template WhatsApp",
                "verbose_name_plural": "Templates WhatsApp",
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
                ),
                ("phone", models.CharField(max_length=20)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Enviada"),
                            ("DELIVERED", "Entregue"),
                            ("READ", "Lida"),
                            ("FAILED", "Falhou"),
                        ],
                        default="SENT",
                        max_length=15,
                    ),
                ),
                ("message_id_meta", models.CharField(blank=True, max_length=100)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.lead",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.whatsapptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem WhatsApp",
                "verbose_name_plural": "Mensagens WhatsApp",
                "ordering": ["-sent_at"],
            },
        ),
    ]
