# Generated by Django 4.2.9 on 2026-03-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_historicalinteraction_created_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["stage", "created_at"], name="crm_lead_stage_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="crm_lead_email_idx"),
        ),
    ]
