# Generated by Django 4.2.9 on 2026-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workflowinstance",
            new_name="workflows_w_status_c535c8_idx",
            old_name="wflow_inst_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowinstance",
            new_name="workflows_w_trigger_9ab160_idx",
            old_name="wflow_inst_trigger_idx",
        ),
        migrations.RemoveField(
            model_name="historicalworkflowstep",
            name="instance",
        ),
        migrations.AlterField(
            model_name="historicalworkflowdefinition",
            name="auto_execute",
            field=models.BooleanField(
                default=True,
                help_text="Executar automaticamente quando o trigger ocorrer",
                verbose_name="Execução Automática",
            ),
        ),
        migrations.AlterField(
            model_name="historicalworkflowdefinition",
            name="steps_definition",
            field=models.JSONField(
                default=list,
                help_text="Lista de passos com configuração",
                verbose_name="Definição dos Passos",
            ),
        ),
        migrations.AlterField(
            model_name="historicalworkflowinstance",
            name="context",
            field=models.JSONField(
                default=dict,
                help_text="Dados passados entre os passos do workflow",
                verbose_name="Contexto",
            ),
        ),
        migrations.AlterField(
            model_name="historicalworkflowstep",
            name="action_config",
            field=models.JSONField(
                default=dict,
                help_text="Parâmetros específicos da ação",
                verbose_name="Configuração",
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="auto_execute",
            field=models.BooleanField(
                default=True,
                help_text="Executar automaticamente quando o trigger ocorrer",
                verbose_name="Execução Automática",
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="steps_definition",
            field=models.JSONField(
                default=list,
                help_text="Lista de passos com configuração",
                verbose_name="Definição dos Passos",
            ),
        ),
        migrations.AlterField(
            model_name="workflowinstance",
            name="context",
            field=models.JSONField(
                default=dict,
                help_text="Dados passados entre os passos do workflow",
                verbose_name="Contexto",
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="action_config",
            field=models.JSONField(
                default=dict,
                help_text="Parâmetros específicos da ação",
                verbose_name="Configuração",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtemplate",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Template de sistema não pode ser alterado",
                verbose_name="Sistema",
            ),
        ),
    ]
