# Generated by Django 4.2.9 on 2026-04-20 16:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="budgetitem",
            new_name="budget_budg_budget__f31588_idx",
            old_name="budget_budg_budget__9c8a21_idx",
        ),
        migrations.RenameIndex(
            model_name="budgetitem",
            new_name="budget_budg_budget__4b4833_idx",
            old_name="budget_budg_budget__2d1e45_idx",
        ),
        migrations.RenameIndex(
            model_name="crowdsourcedprice",
            new_name="budget_crow_status_587b15_idx",
            old_name="budget_crow_status_7f8e92_idx",
        ),
        migrations.RenameIndex(
            model_name="crowdsourcedprice",
            new_name="budget_crow_categor_e0fa79_idx",
            old_name="budget_crow_categor_1a2b34_idx",
        ),
        migrations.RenameIndex(
            model_name="crowdsourcedprice",
            new_name="budget_crow_reporte_279532_idx",
            old_name="budget_crow_reporte_5c6d78_idx",
        ),
        migrations.RenameIndex(
            model_name="crowdsourcedprice",
            new_name="budget_crow_item_na_af7764_idx",
            old_name="budget_crow_item_na_9e0f12_idx",
        ),
        migrations.RenameIndex(
            model_name="localpriceitem",
            new_name="budget_loca_categor_2931eb_idx",
            old_name="budget_loca_categor_5c9f68_idx",
        ),
        migrations.RenameIndex(
            model_name="localpriceitem",
            new_name="budget_loca_name_421f90_idx",
            old_name="budget_loca_name_5a2c68_idx",
        ),
        migrations.RenameIndex(
            model_name="localpriceitem",
            new_name="budget_loca_code_0ac562_idx",
            old_name="budget_loca_code_6b9f12_idx",
        ),
        migrations.RenameIndex(
            model_name="localpriceitem",
            new_name="budget_loca_categor_ff29e4_idx",
            old_name="budget_loca_categor_e3b2a1_idx",
        ),
        migrations.RenameIndex(
            model_name="simplebudget",
            new_name="budget_simp_project_1033a3_idx",
            old_name="budget_simp_project_8a9c21_idx",
        ),
        migrations.RenameIndex(
            model_name="simplebudget",
            new_name="budget_simp_created_752204_idx",
            old_name="budget_simp_created_3b4f56_idx",
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preço Unitário",
            ),
        ),
        migrations.AlterField(
            model_name="crowdsourcedprice",
            name="date_observed",
            field=models.DateField(
                help_text="Quando viu o preço", verbose_name="Data Observada"
            ),
        ),
        migrations.AlterField(
            model_name="crowdsourcedprice",
            name="location",
            field=models.CharField(
                help_text="Ex: Praia, Achada Grande",
                max_length=100,
                verbose_name="Localização",
            ),
        ),
        migrations.AlterField(
            model_name="crowdsourcedprice",
            name="price_cve",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Preço (CVE)",
            ),
        ),
        migrations.AlterField(
            model_name="crowdsourcedprice",
            name="receipt_photo",
            field=models.URLField(
                blank=True,
                help_text="URL da foto no S3",
                verbose_name="Foto do Recibo/Preço",
            ),
        ),
        migrations.AlterField(
            model_name="crowdsourcedprice",
            name="supplier",
            field=models.CharField(
                blank=True,
                help_text="Opcional",
                max_length=100,
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="localpriceitem",
            name="code",
            field=models.CharField(
                help_text="Ex: IMOS-001, CV-045",
                max_length=20,
                unique=True,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="localpriceitem",
            name="ifc_class",
            field=models.CharField(
                blank=True,
                help_text="Ex: IfcWall, IfcSlab, IfcDoor",
                max_length=50,
                verbose_name="Classe IFC",
            ),
        ),
        migrations.AlterField(
            model_name="localpriceitem",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Verificado por administrador",
                verbose_name="Verificado",
            ),
        ),
        migrations.AlterField(
            model_name="localpriceitem",
            name="name",
            field=models.CharField(
                help_text="Ex: Cimento CP350 50kg", max_length=200, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="localpriceitem",
            name="price_santiago",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preço Santiago (CVE)",
            ),
        ),
        migrations.AlterField(
            model_name="localpriceitem",
            name="source",
            field=models.CharField(
                help_text="Ex: Cimpor CV, Loja Praia, Crowdsourced",
                max_length=100,
                verbose_name="Fonte",
            ),
        ),
        migrations.AlterField(
            model_name="simplebudget",
            name="contingency_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Contingência (%)",
            ),
        ),
        migrations.AlterField(
            model_name="simplebudget",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="simplebudget",
            name="island",
            field=models.CharField(
                choices=[
                    ("SANTIAGO", "Santiago"),
                    ("SAO_VICENTE", "São Vicente"),
                    ("SAL", "Sal"),
                    ("BOA_VISTA", "Boa Vista"),
                    ("SANTO_ANTAO", "Santo Antão"),
                    ("SAO_NICOLAU", "São Nicolau"),
                    ("FOGO", "Fogo"),
                    ("BRAVA", "Brava"),
                    ("MAIO", "Maio"),
                ],
                default="SANTIAGO",
                help_text="Para aplicar preços correctos",
                max_length=20,
                verbose_name="Ilha",
            ),
        ),
        migrations.AlterField(
            model_name="simplebudget",
            name="name",
            field=models.CharField(
                help_text="Ex: Orçamento Preliminar",
                max_length=200,
                verbose_name="Nome",
            ),
        ),
        migrations.AlterField(
            model_name="simplebudget",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado em"),
        ),
    ]
