# Generated by Django 4.2.9 on 2026-04-20 17:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0004_projectdocument_historicalprojectdocument"),
        ("construction", "0004_remove_constructionphoto_created_by_and_more"),
        (
            "budget",
            "0002_rename_budget_budg_budget__9c8a21_idx_budget_budg_budget__f31588_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descrição/Factura"),
                ),
                (
                    "amount_cve",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor (CVE)",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Despesa",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Fornecedor"
                    ),
                ),
                (
                    "receipt_photo",
                    models.URLField(
                        blank=True,
                        help_text="URL da foto no S3",
                        verbose_name="Foto do Recibo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="budget.budgetitem",
                        verbose_name="Item do Orçamento",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_expenses",
                        to="projects.project",
                        verbose_name="Projecto",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="construction.constructiontask",
                        verbose_name="Tarefa de Construção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa de Obra",
                "verbose_name_plural": "Despesas de Obra",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConstructionAdvance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor_name",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Empreiteiro/Fornecedor"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Motivo do Adiantamento"),
                ),
                (
                    "amount_cve",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor Adiantado (CVE)",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data do Pagamento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PAID", "Pago"),
                            ("SETTLED", "Liquidado/Compensado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "settlement_date",
                    models.DateField(
                        blank=True,
                        help_text="Data em que o adiantamento foi compensado em facturas",
                        null=True,
                        verbose_name="Data de Liquidação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_advances",
                        to="projects.project",
                        verbose_name="Projecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adiantamento de Obra",
                "verbose_name_plural": "Adiantamentos de Obra",
                "ordering": ["-date"],
            },
        ),
    ]
